#!/bin/bash
if [ -x $0.local ]; then
    echo TRY LOCAL/OLD HOOK
    $0.local "$@" || exit $?
fi
if [ -x hooks/$(basename $0) ]; then
    echo TRY NEW HOOK
    hooks/$(basename $0) "$@" || exit $?
fi
